### ISSUE TITLE
Using with cross origin 

### ISSUE THREAD

**Issue by fxfactorial** [WebReflection/pocket.io#1]
My client web socket will access a different web socket server than the origin, so I need cross origin to work. 

I tried the socket.io approach as described here: 

https://stackoverflow.com/questions/24058157/socket-io-node-js-cross-origin-request-blocked

but it was not accepted. 

Can you give me some pointers or support this API?

**Comment by WebReflection** [comment]
My goal here is to keep it simple and light so, for the time being, if you need socket.io features that don't work here, keep using socket.io.

I'll have a look when I have time though, maybe it's easy to bring that in.

**Comment by fxfactorial** [comment]
I wasn't using socket.io to begin from, so was hoping could start from this lib as first. will move to socket.io, thanks!

**Comment by WebReflection** [comment]
After having a quick look, I don't think I have time to implement CORS with pocket.io

For very specific cases where socket.io is already battle tested and the most adopted solution I have no intention to compete with it.

This is supposed to be a super lightweight alternative for IoT related projects or connections to your own server.

Regards
