### ISSUE TITLE
Firefox can’t establish a connection to the server 

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/pocket.io#2]
If you visit https://conpa.now.sh/ with Firefox you get

`Firefox can’t establish a connection to the server at wss://conpa.now.sh/pocket.io/.`

With Chrome it is ok.

It worked correctly. And I didn't updated the code.
I think something it is changed on Firefox side.

Any hint?

**Comment by WebReflection** [comment]
File a Firefox bug 🤷‍♂️

No or other hints, sorry, I'm also on vacation in Indonesia so no way/time to look at that

**Comment by albertosantini** [comment]
Ah yes... you are off... Sorry for the disturb.

**Comment by albertosantini** [comment]
I hope it is not about the certificate

https://bugzilla.mozilla.org/show_bug.cgi?id=594502

**Comment by albertosantini** [comment]
I think it is about the self-signed certificate.
