### ISSUE TITLE
add an option to `.use` middleware

### ISSUE THREAD

**Issue by tvardy** [WebReflection/pocket.io#5]
From all the socket.io features I think this would be the most interesting to re-use in this lib

**Comment by WebReflection** [comment]
isn't that just an express `use` delegate? what should this method do in here? 🤔

**Comment by tvardy** [comment]
it's "inspired" by express... (https://socket.io/docs/v3/middlewares/)
and it's also possible to use middleware created for express (https://socket.io/docs/v3/middlewares/#Compatibility-with-Express-middleware)

**Comment by WebReflection** [comment]
yeah, so , this module is about minimalism ... the `.use` concept AFAIK doesn't exist in NodeJS, so any extra socket.io feature out there *might* not be implemented because if anything more tested and complex is needed, socket.io *is* the way to go.

Does this make sense?

**Comment by tvardy** [comment]
You might be right ;)
